// <auto-generated />
using System;
using Meetly.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meetly.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Meetly.Repository.Entity.EventAvailableDates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "DayOfWeek")
                        .IsUnique()
                        .HasFilter("\"DayOfWeek\" IS NOT NULL");

                    b.HasIndex("EventId", "SpecificDate")
                        .IsUnique()
                        .HasFilter("\"SpecificDate\" IS NOT NULL");

                    b.ToTable("EventAvailableDates", t =>
                        {
                            t.HasCheckConstraint("CK_EventAvailableDates_DayOfWeek", "\"DayOfWeek\" IS NULL OR \"DayOfWeek\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_EventAvailableDates_Selection", "(\"SpecificDate\" IS NOT NULL AND \"DayOfWeek\" IS NULL) OR (\"SpecificDate\" IS NULL AND \"DayOfWeek\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventEmails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Email")
                        .IsUnique();

                    b.ToTable("EventEmails");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Username")
                        .IsUnique();

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.Events", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("DailyEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DailyStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("FinalDate")
                        .HasColumnType("date");

                    b.Property<int?>("FinalDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("FinalEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("FinalStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Events_DailyTime", "\"DailyStartTime\" < \"DailyEndTime\"");

                            t.HasCheckConstraint("CK_Events_EventType", "\"EventType\" IN (1, 2)");

                            t.HasCheckConstraint("CK_Events_FinalSelection", "(\"FinalDate\" IS NULL AND \"FinalDayOfWeek\" IS NULL AND \"FinalStartTime\" IS NULL AND \"FinalEndTime\" IS NULL) OR (((\"FinalDate\" IS NOT NULL AND \"FinalDayOfWeek\" IS NULL) OR (\"FinalDate\" IS NULL AND \"FinalDayOfWeek\" IS NOT NULL)) AND \"FinalStartTime\" IS NOT NULL AND \"FinalEndTime\" IS NOT NULL AND \"FinalStartTime\" < \"FinalEndTime\")");

                            t.HasCheckConstraint("CK_Events_Status", "\"Status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Meetly.Repository.Entity.TimeSlots", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("DayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SpecificDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "DayOfWeek");

                    b.HasIndex("EventId", "SpecificDate");

                    b.HasIndex("ParticipantId", "EventId");

                    b.ToTable("TimeSlots", t =>
                        {
                            t.HasCheckConstraint("CK_TimeSlots_DayOfWeek", "\"DayOfWeek\" IS NULL OR \"DayOfWeek\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_TimeSlots_Selection", "(\"SpecificDate\" IS NOT NULL AND \"DayOfWeek\" IS NULL) OR (\"SpecificDate\" IS NULL AND \"DayOfWeek\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_TimeSlots_Time", "\"StartTime\" < \"EndTime\"");
                        });
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventAvailableDates", b =>
                {
                    b.HasOne("Meetly.Repository.Entity.Events", "Event")
                        .WithMany("AvailableDates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventEmails", b =>
                {
                    b.HasOne("Meetly.Repository.Entity.Events", "Event")
                        .WithMany("Emails")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventParticipants", b =>
                {
                    b.HasOne("Meetly.Repository.Entity.Events", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.TimeSlots", b =>
                {
                    b.HasOne("Meetly.Repository.Entity.Events", "Event")
                        .WithMany("TimeSlots")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meetly.Repository.Entity.EventParticipants", "Participant")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ParticipantId", "EventId")
                        .HasPrincipalKey("Id", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.EventParticipants", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Meetly.Repository.Entity.Events", b =>
                {
                    b.Navigation("AvailableDates");

                    b.Navigation("Emails");

                    b.Navigation("Participants");

                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
